services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${CURRENT_UID}
        GID: ${CURRENT_GID}
    environment:
      - UID=${CURRENT_UID}
      - GID=${CURRENT_GID}
    working_dir: /var/www
    volumes:
      - .:/var/www

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${CURRENT_UID}
        GID: ${CURRENT_GID}
    environment:
      - UID=${CURRENT_UID}
      - GID=${CURRENT_GID}
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php public/consumer.php
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started

volumes:
  db_data:
  vendor:
